services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    # depends_on:
    #   - redis

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
